# Generated by Django 4.0.4 on 2022-06-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RockzApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocketblog',
            name='Rocket_LandingDate',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='rocketblog',
            name='Rocket_LaunchDate',
            field=models.CharField(max_length=10),
        ),
    ]
